name: Preprocess, Train, Test, Validate

env:
  RUN_ID: ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit and integration tests
        run: |
          python -m pytest

      - name: Run preprocessing
        run: |
          python preprocess.py \
            --input data/HDFS.log \
            --out_df output/output.csv

      - name: Upload preprocessed data
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data-${{ env.RUN_ID }}
          path: output/output.csv

      - name: Train model
        run: |
          python train.py --run-id ${{ env.RUN_ID }}

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            models/model_${{ env.RUN_ID }}.pkl
            models/metrics_${{ env.RUN_ID }}.json

      - name: Check metrics thresholds
        run: |
          python check_metrics.py ${{ env.RUN_ID }}

